Library/Models/Author.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [Column(TypeName = "Date")]
        public DateTime? DateOfBirth { get; set; }

        [Column(TypeName = "Date")]
        public DateTime? DateOfDeath { get; set; }

        public IEnumerable<Book>? Books { get; set; }
    }
}

Library/Models/Book.cs
using System.Collections;
using System.Collections.Generic;

namespace Library.Models
{
    public class Book
    {
        public int Id { get; set; }
        
        public string Title { get; set; }
        public string? Summary { get; set; }
        public string? Isbn { get; set; }
        public Author? Author { get; set; }
        public ICollection<Genre> genres { get; set; }
        public Language language { get; set; }

        public IEnumerable<BookInstance>? Instances { get; set; }

    }
}

Library/Models/BookInstance.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class BookInstance
    {
        public Guid Id { get; set; }
        
        [Column(TypeName = "Date")]
        public DateTime DueBack { get; set; }
        public LoanStatus LoanStatus { get; set; }
        public Book Book { get; set; }
        public string Imprint { get; set; }
    }

    public enum LoanStatus
    {
        Maintenance,
        OnLoan,
        Available,
        Reserved
    }
}

Library/Models/ErrorViewModel.cs
namespace Library.Models
{
    
public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}
}

Library/Models/Genre.cs
namespace Library.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string name { get; set; }
    }
}

Library/Models/Language.cs
namespace Library.Models
{
    public class Language
    {
        public int Id { get; set; }
        public string name { get; set; }
    }
}

Library/Controllers/AuthorController.cs
using System.Threading.Tasks;
using LocalLibrary.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Library.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ILogger<AuthorController> _logger;

        private readonly LibraryContext _context;
        
        public AuthorController(ILogger<AuthorController> logger, LibraryContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async  Task<IActionResult> Index()
        {
            var authors=  await _context.Authors.ToListAsync();
            return View(authors);
        }
        
        public async Task<IActionResult> Detail(int id)
        {
            var author = await _context.Authors
                .Include(a => a.Books)
                .FirstOrDefaultAsync(a => a.Id == id);
            if (author == null)
            {
                _logger.Log(LogLevel.Information,"Author not found");
                return NotFound();
            }
            _logger.Log(LogLevel.Information,"Accessed to Author Detail Page");
            return View(author);
        }
    }
}

Library/Controllers/BookController.cs
using System.Threading.Tasks;
using Library.Models;
using LocalLibrary.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly LibraryContext _context;
        // GET
        public BookController(LibraryContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var books = await _context.Books.
                Include(book => book.Author).ToListAsync();
            return View(books);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var book = await _context.Books
                .Include(b => b.Instances)
                .Include(b => b.Author)
                .FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        
        public  IActionResult Create()
        {
            return View();
        }
    }
}

Library/Views/Author/Detail.cshtml
@model Author

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
  

<h1>Author: @Model!.FirstName @Model.LastName</h1>
<p>@Model.DateOfBirth - @Model.DateOfDeath</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

    <dl>
        @foreach (var book in @Model.Books!.Select((item,index) => (item,index)))
        {
            <dt><a asp-action="Detail" asp-controller="Book" asp-route-id="@book.item.Id">@book.item.Title</a> (@book.index)</dt>
            <dd>@book.item.Summary</dd>
        }
    </dl>

</div>

Library/Views/Author/Index.cshtml
@model IEnumerable<Author>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Author index page</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfDeath)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var author in Model) {
    <tr>
            <td>
             
                <a class="nav-link"  asp-action="Detail" asp-route-id="@author.Id">
                    @Html.DisplayFor(modelItem => author.FirstName)
                </a>

            </td>
            <td>
                <a class="nav-link"  asp-action="Detail" asp-route-id="@author.Id">
                    @Html.DisplayFor(modelItem => author.LastName)
                </a>
            </td>
            <td>
                @author.DateOfBirth?.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => author.DateOfDeath)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
}
    </tbody>
</table>

Library/Views/Book/Create.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

Library/Views/Book/Detail.cshtml
@model Book

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
    
}

<h2>@Model?.Title</h2>
<hr/>
<p><strong>Author:</strong> <a asp-action="Detail" asp-controller="Author" 
                               asp-route-id="@Model!.Author!.Id">@Model?.Author?.FirstName @Model?.Author?.LastName</a></p>
<p><strong>Summary:</strong> @Model?.Summary</p>
<p><strong>ISBN:</strong> @Model?.Isbn</p> 
<p><strong>Language:</strong> @Model?.language</p>  
<p><strong>Genre:</strong>@Model?.genres</p>

<div class="mt-3">
<h4>Copies</h4>
    <hr>
   @foreach (var instance in @Model!.Instances!)
   {
       var loanStatusClass = @instance.LoanStatus switch
       {
           LoanStatus.Available => "text-success",
           LoanStatus.Maintenance => "text-warning",
           LoanStatus.OnLoan => "text-primary",
           LoanStatus.Reserved => "text-info",
           _ => "text-primary"
       };
        <p class="@loanStatusClass">@instance.LoanStatus</p>
        <p><strong>Imprint:</strong> @instance.Imprint</p>
        <p class="text-muted"><strong>Id:</strong> @instance.Id</p>
    }
</div>

Library/Views/Book/Index.cshtml
@model IEnumerable<Book>

@{
    ViewBag.Title = "Book";
    Layout = "_Layout";
}

<h2>Book index page</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Summary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Isbn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.genres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author!.FirstName )
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author!.LastName )
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var book in Model) {
    <tr>
            <td>
                <a class="nav-link"  asp-action="Detail" asp-route-id="@book.Id">
                    @Html.DisplayFor(modelItem => book.Title)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.Summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.Isbn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.genres)
            </td>
        <td>
                <a class="nav-link" asp-controller="Author" asp-action="Detail" asp-route-id="@book.Author!.Id">
                    @Html.DisplayFor(modelItem => book.Author!.FirstName)
                </a>
        </td>
            <td>
                <a class="nav-link" asp-controller="Author" asp-action="Detail" asp-route-id="@book.Author!.Id">
                    @Html.DisplayFor(modelItem => book.Author!.LastName)
                </a>
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                <a asp-action="Detail" asp-route-id="@book.Id">Details</a>
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
}
    </tbody>
</table>

Library/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var numberOfBooks = ViewData["numberOfBooks"]!;
    var numberOfAuthors = ViewData["numberOfAuthors"]!; 
    var numberOfBookInstances = ViewData["numberOfBookInstances"]!;
    var numberOfAvailableInstances = ViewData["numberOfAvailableInstances"];
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <hr>
    <div class="container">
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> @numberOfBooks</li>
        <li><strong>Copies:</strong> @numberOfBookInstances</li>
        <li><strong>Copies available:</strong> @numberOfAvailableInstances</li>
        <li><strong>Authors:</strong> @numberOfAuthors</li>
    </ul>
    </div>
</div>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">All Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">All Authors</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>